#ifndef ROBOTMAP_H
#define ROBOTMAP_H

#include "WPILib.h"

#define FRONT_LEFT_MOTOR_CHANNEL 12
#define FRONT_RIGHT_MOTOR_CHANNEL 13
#define BACK_LEFT_MOTOR_CHANNEL 15
#define BACK_RIGHT_MOTOR_CHANNEL 14

#define ENCODER_FRONT_LEFT_PORTS 4, 5
#define ENCODER_FRONT_RIGHT_PORTS 2, 3
#define ENCODER_BACK_LEFT_PORTS 8, 9
#define ENCODER_BACK_RIGHT_PORTS 6, 7

#endif
